# Generated by Django 4.2.15 on 2024-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="order"),
        ),
    ]
