# Generated by Django 4.2.15 on 2024-09-04 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_page_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "pagina",
                "verbose_name_plural": "paginas",
            },
        ),
    ]
