# Generated by Django 4.2.15 on 2024-09-04 23:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_page_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["-order", "title"],
                "verbose_name": "pagina",
                "verbose_name_plural": "paginas",
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Contenido"),
        ),
    ]
